Second Push updates
getting errors

Main.java:7: error: cannot find symbol
        ProcessManager manager = new ProcessManager();
        ^
  symbol:   class ProcessManager
  location: class Main
Main.java:7: error: cannot find symbol
        ProcessManager manager = new ProcessManager();
                                     ^
  symbol:   class ProcessManager
  location: class Main
Main.java:39: error: Process is abstract; cannot be instantiated
                    Process newProcess = new Process(processID, name, user, executionTime);
                                         ^
3 errors

- need to fix and debug